# Generated by Django 4.2.16 on 2026-08-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
