# Generated by Django 4.2.16 on 2026-08-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_preparing_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='orders.order'),
        ),
    ]
