# Generated by Django 4.2.16 on 2026-09-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_parent_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
    ]
