# Generated by Django 4.2.16 on 2026-09-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tracks_daily_portions',
            field=models.BooleanField(default=False),
        ),
    ]
