# Generated by Django 4.2.16 on 2026-10-05 07:19

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_tracks_daily_portions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', django.db.models.functions.text.Lower('name'), 'id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__sort_order', 'sort_order', django.db.models.functions.text.Lower('name'), 'id']},
        ),
    ]
