# Generated by Django 4.2.16 on 2026-07-22 15:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('kitchen_enabled', models.BooleanField(default=True)),
                ('billing_enabled', models.BooleanField(default=True)),
                ('realtime_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
