# Generated by Django 4.2.16 on 2026-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_org_identity_and_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
