# Generated by Django 4.2.16 on 2026-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='razorpay_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
