# Generated by Django 4.2.16 on 2026-09-29 07:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_razorpay_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='RestaurantRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=32)),
                ('contact_email', models.EmailField(max_length=254)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('plan_tier', models.CharField(choices=[('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('ENTERPRISE', 'Enterprise')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING_SIGNUP', 'Waiting for signup'), ('COMPLETED', 'Completed')], default='PENDING_SIGNUP', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'restaurant_registrations',
            },
        ),
    ]
