# Generated by Django 4.2.16 on 2026-09-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_gst_number_and_self_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='customer_ordering_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='server_staff_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
