# Generated by Django 4.2.16 on 2026-10-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_customer_ordering_and_server_staff_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='restaurantregistration',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurantregistration',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
