# Generated by Django 4.2.16 on 2026-10-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurant_pan_and_business_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='realtime_enabled',
        ),
    ]
