# Generated by Django 4.2.16 on 2026-10-05 07:19

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_restaurant_realtime_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': [django.db.models.functions.text.Lower('name'), 'id']},
        ),
    ]
