# Generated by Django 4.2.16 on 2026-10-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_case_insensitive_name_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('PAYMENT_DUE', 'Payment due')], default='ACTIVE', max_length=16),
        ),
    ]
