# Generated by Django 4.2.16 on 2026-07-27 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discrepancy_acknowledged', models.BooleanField(default=False)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_shifts', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'cashier_shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cashier',), name='one_open_shift_per_cashier'),
        ),
    ]
