# Generated by Django 4.2.16 on 2026-08-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_takeaway'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bill',
            name='bill_has_exactly_one_of_session_or_order',
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order__isnull', True), ('session__isnull', False)), models.Q(('order__isnull', False), ('session__isnull', True)), _connector='OR'), name='bill_has_exactly_one_of_session_or_order'),
        ),
    ]
