# Generated by Django 4.2.16 on 2026-08-19 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_bill_bill_has_exactly_one_of_session_or_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='discrepancy_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='discrepancy_reason',
            field=models.TextField(blank=True),
        ),
    ]
