# Generated by Django 4.2.16 on 2026-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_cashiershift_discrepancy_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
