# Generated by Django 4.2.16 on 2026-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bill_amount_received_bill_change_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method_detail',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=12),
        ),
    ]
