"""Branch scoping for the AI and reporting endpoints (2026-09-29, per Karwin).

Tested live on production first: AI Insights generated by an Admin were
saved branch-less, so the Voyager-Ekm dashboard's AI card stayed empty,
and AI Chat, the AI End of Day Report, the End of Day Review, low-stock
alerts and the AI Prep Forecast all handed a Manager pinned to one branch
every branch's revenue and stock. The rule these tests pin down is
core.tenancy.resolve_report_branch: a Manager always gets their own
branch; an Admin gets the whole restaurant unless ?branch= narrows it.
"""
import importlib
import json
import uuid
from datetime import timedelta
from decimal import Decimal

import pytest
from django.utils import timezone
from rest_framework.test import APIClient

from apps.inventory import services as inventory_services
from apps.inventory.models import AIInsight, Ingredient
from apps.orders.models import Order, OrderItem
from apps.restaurant.models import Branch
from apps.tables.models import Table, TableSession

pytestmark = pytest.mark.django_db


def _client_for(user):
    from apps.authentication.serializers import DineOSTokenObtainPairSerializer

    client = APIClient()
    client.credentials(HTTP_AUTHORIZATION=f"Bearer {DineOSTokenObtainPairSerializer.get_token(user).access_token}")
    return client


@pytest.fixture
def branch_b(restaurant):
    return Branch.objects.create(restaurant=restaurant, name="Second Branch")


@pytest.fixture
def manager_a(restaurant, branch):
    """A Manager pinned to `branch` - the conftest manager has no branch,
    which is exactly why none of the existing tests caught the leak."""
    from apps.authentication.models import User

    user = User.objects.create_user(
        email="manager-a@test.dineos", password="Test@1234", role="MANAGER", name="Manager A",
        restaurant=restaurant, branch=branch,
    )
    return user, _client_for(user)


@pytest.fixture
def chicken_a(restaurant, branch):
    return Ingredient.objects.create(
        restaurant=restaurant, branch=branch, name="Chicken", unit="KG",
        current_stock=Decimal("1.00"), minimum_stock_level=Decimal("5.00"),
    )


@pytest.fixture
def paneer_b(restaurant, branch_b):
    return Ingredient.objects.create(
        restaurant=restaurant, branch=branch_b, name="Paneer", unit="KG",
        current_stock=Decimal("2.00"), minimum_stock_level=Decimal("8.00"),
    )


@pytest.fixture
def table_a(restaurant, branch):
    return Table.objects.create(restaurant=restaurant, branch=branch, table_number="A1", capacity=4)


@pytest.fixture
def table_b(restaurant, branch_b):
    return Table.objects.create(restaurant=restaurant, branch=branch_b, table_number="B1", capacity=4)


def _paid_bill(table, menu_item, quantity):
    from apps.billing import services as billing_services
    from apps.orders import services as order_services
    from apps.tables import services as table_services

    session, _ = table_services.get_or_create_active_session(table.id)
    order_services.place_order(session.id, [{"menu_item_id": menu_item.id, "quantity": quantity}])
    return billing_services.pay_bill(session.id, "CASH", None)


def _order_on(table, menu_item, quantity, when):
    # Same shape as tests/test_prep_forecast.py: a historical, already
    # closed visit so several can sit on one table.
    session = TableSession.objects.create(table=table, status=TableSession.Status.CLOSED)
    order = Order.objects.create(table=table, session=session, order_type="DINE_IN", status="SERVED")
    Order.objects.filter(id=order.id).update(placed_at=when)
    OrderItem.objects.create(order=order, menu_item=menu_item, quantity=quantity, unit_price=menu_item.price)


def _snapshot(messages):
    return json.loads(messages[0]["content"].split("snapshot: ", 1)[1])


# ---- AI Insights ------------------------------------------------------------

def test_admin_generated_insights_carry_their_ingredients_branch(
    admin_client, manager_a, branch, branch_b, chicken_a, paneer_b, monkeypatch,
):
    _, admin = admin_client
    _, manager = manager_a

    def fake_generate_json(system_prompt, user_prompt, **kwargs):
        return {"insights": [
            {"ingredient_id": f["ingredient_id"], "severity": "CRITICAL",
             "headline": f"{f['ingredient_name']} is below minimum", "recommended_action": "Reorder"}
            for f in json.loads(user_prompt)["ingredients"]
        ]}

    monkeypatch.setattr("core.ai_client.generate_json", fake_generate_json)

    response = admin.post("/v1/inventory/ai-insights/generate/")

    assert response.status_code == 201, response.data
    assert AIInsight.objects.get(ingredient=chicken_a).branch_id == branch.id
    assert AIInsight.objects.get(ingredient=paneer_b).branch_id == branch_b.id

    dashboard = admin.get(f"/v1/admin/dashboard/?branch={branch.id}").data
    assert dashboard["ai_daily_insight"]["headline"] == "Chicken is below minimum"

    feed = manager.get("/v1/inventory/ai-insights/").data
    rows = feed["results"] if "results" in feed else feed
    assert [r["ingredient_name"] for r in rows] == ["Chicken"]


def test_backfill_gives_branchless_insights_their_ingredients_branch(restaurant, branch, chicken_a):
    from django.apps import apps as django_apps

    legacy = Ingredient.objects.create(
        restaurant=restaurant, name="Legacy Oil", unit="L",
        current_stock=Decimal("0.00"), minimum_stock_level=Decimal("2.00"),
    )
    stranded = AIInsight.objects.create(restaurant=restaurant, ingredient=chicken_a, severity="ALERT", headline="x")
    unbranched = AIInsight.objects.create(restaurant=restaurant, ingredient=legacy, severity="ALERT", headline="y")

    migration = importlib.import_module("apps.inventory.migrations.0008_backfill_ai_insight_branch")
    migration.forwards(django_apps, None)

    stranded.refresh_from_db()
    unbranched.refresh_from_db()
    assert stranded.branch_id == branch.id
    assert unbranched.branch_id is None  # its ingredient has no branch to give


# ---- low-stock alerts, and the branch rule itself ----------------------------

def test_low_stock_alerts_follow_the_callers_branch(admin_client, manager_a, branch, branch_b, chicken_a, paneer_b):
    _, admin = admin_client
    _, manager = manager_a
    url = "/v1/admin/ai/low-stock-alerts/"

    assert {a["name"] for a in manager.get(url).data} == {"Chicken"}
    assert {a["name"] for a in admin.get(url).data} == {"Chicken", "Paneer"}
    assert {a["name"] for a in admin.get(f"{url}?branch={branch_b.id}").data} == {"Paneer"}

    # A Manager may name their own branch, never another one.
    assert manager.get(f"{url}?branch={branch.id}").status_code == 200
    assert manager.get(f"{url}?branch={branch_b.id}").status_code == 403

    # A bad filter is an error, never an unfiltered answer.
    assert admin.get(f"{url}?branch=not-a-uuid").status_code == 400
    assert admin.get(f"{url}?branch={uuid.uuid4()}").status_code == 404


def test_admin_cannot_name_another_restaurants_branch(admin_client):
    from apps.restaurant.models import Restaurant

    _, admin = admin_client
    foreign = Branch.objects.create(restaurant=Restaurant.objects.create(name="Elsewhere", slug="elsewhere"), name="X")

    assert admin.get(f"/v1/admin/ai/low-stock-alerts/?branch={foreign.id}").status_code == 404


# ---- End of Day ---------------------------------------------------------------

def test_eod_review_counts_only_the_managers_branch(admin_client, manager_a, branch, branch_b, table_a, table_b, menu_item, paneer_b):
    _, admin = admin_client
    _, manager = manager_a
    bill_a = _paid_bill(table_a, menu_item, 1)
    bill_b = _paid_bill(table_b, menu_item, 2)
    inventory_services.record_wastage(paneer_b.id, Decimal("1.00"), "SPOILED")

    mine = manager.get("/v1/admin/eod-review/").data
    assert mine["branch"] == str(branch.id)
    assert mine["tables_served"] == 1
    assert Decimal(str(mine["total_collected"])) == bill_a.total_amount
    assert mine["wastage_entries_count"] == 0  # the spoiled Paneer is Second Branch's

    everything = admin.get("/v1/admin/eod-review/").data
    assert everything["branch"] is None
    assert everything["tables_served"] == 2
    assert everything["wastage_entries_count"] == 1

    theirs = admin.get(f"/v1/admin/eod-review/?branch={branch_b.id}").data
    assert Decimal(str(theirs["total_collected"])) == bill_b.total_amount

    assert manager.get(f"/v1/admin/eod-review/?branch={branch_b.id}").status_code == 403


def test_ai_eod_report_hands_the_model_only_the_managers_branch(
    manager_a, branch, table_a, table_b, menu_item, chicken_a, paneer_b, monkeypatch,
):
    _, manager = manager_a
    _paid_bill(table_a, menu_item, 1)
    _paid_bill(table_b, menu_item, 2)
    captured = {}

    def fake_generate_json(system_prompt, user_prompt, **kwargs):
        captured["facts"] = json.loads(user_prompt)
        return {"summary": "ok", "recommendations": []}

    monkeypatch.setattr("core.ai_client.generate_json", fake_generate_json)

    response = manager.get("/v1/admin/ai/eod-report/")

    assert response.status_code == 200, response.data
    assert response.data["tables_served"] == 1
    facts = captured["facts"]
    assert facts["scope"] == f"{branch.name} branch only"
    assert facts["today_summary"]["tables_served"] == 1
    assert [i["name"] for i in facts["low_or_critical_stock_ingredients"]] == ["Chicken"]


# ---- AI Chat --------------------------------------------------------------------

def test_ai_chat_context_follows_the_callers_branch(
    admin_client, manager_a, branch, branch_b, table_a, table_b, menu_item, chicken_a, paneer_b, monkeypatch,
):
    _, admin = admin_client
    _, manager = manager_a
    _paid_bill(table_a, menu_item, 1)
    _paid_bill(table_b, menu_item, 2)
    captured = []
    monkeypatch.setattr(
        "core.ai_client.generate_reply", lambda system_prompt, messages, **k: captured.append(messages) or "noted",
    )

    assert manager.post("/v1/admin/ai/chat/messages/", {"content": "What's low?"}, format="json").status_code == 201
    mine = _snapshot(captured[-1])
    assert mine["scope"] == f"{branch.name} branch only"
    assert [i["name"] for i in mine["low_or_critical_stock_ingredients"]] == ["Chicken"]
    assert mine["today"]["tables_served"] == 1
    assert "today_by_branch" not in mine

    assert admin.post("/v1/admin/ai/chat/messages/", {"content": "What's low?"}, format="json").status_code == 201
    everything = _snapshot(captured[-1])
    stock = {i["name"]: i["branch"] for i in everything["low_or_critical_stock_ingredients"]}
    assert stock == {"Chicken": branch.name, "Paneer": branch_b.name}
    assert everything["today"]["tables_served"] == 2
    assert {row["branch"] for row in everything["today_by_branch"]} == {branch.name, branch_b.name}

    # Refused before anything is saved or sent.
    response = manager.post(f"/v1/admin/ai/chat/messages/?branch={branch_b.id}", {"content": "Theirs?"}, format="json")
    assert response.status_code == 403
    assert len(captured) == 2


# ---- AI Prep Forecast -------------------------------------------------------------

def test_prep_forecast_defaults_to_the_managers_branch(
    admin_client, manager_a, branch, branch_b, table_a, table_b, menu_item, monkeypatch,
):
    _, admin = admin_client
    _, manager = manager_a
    today = timezone.localdate()
    last_week = timezone.make_aware(timezone.datetime.combine(today - timedelta(weeks=1), timezone.datetime.min.time()))
    _order_on(table_a, menu_item, 4, last_week)
    _order_on(table_b, menu_item, 9, last_week)

    def fake_generate_json(system_prompt, user_prompt, **kwargs):
        dishes = json.loads(user_prompt)["dishes"]
        return {"forecasts": [{"menu_item_id": d["menu_item_id"], "headline": "h", "reasoning": "r"} for d in dishes]}

    monkeypatch.setattr("core.ai_client.generate_json", fake_generate_json)

    mine = manager.get("/v1/prepared-dishes/prep-forecast/").data["forecasts"][0]
    assert mine["occurrence_quantities"] == [4, 0, 0, 0]

    everything = admin.get("/v1/prepared-dishes/prep-forecast/").data["forecasts"][0]
    assert everything["occurrence_quantities"] == [13, 0, 0, 0]

    assert manager.get(f"/v1/prepared-dishes/prep-forecast/?branch={branch_b.id}").status_code == 403
    assert admin.get("/v1/prepared-dishes/prep-forecast/?branch=not-a-uuid").status_code == 400


def test_prep_forecast_pairs_each_quantity_with_its_date(manager_client, table, menu_item, monkeypatch):
    _, client = manager_client
    today = timezone.localdate()
    for weeks_ago, quantity in ((1, 2), (2, 1), (3, 8)):
        when = timezone.make_aware(timezone.datetime.combine(today - timedelta(weeks=weeks_ago), timezone.datetime.min.time()))
        _order_on(table, menu_item, quantity, when)
    monkeypatch.setattr(
        "core.ai_client.generate_json",
        lambda s, u, **k: {"forecasts": [{"menu_item_id": d["menu_item_id"], "headline": "h", "reasoning": "r"}
                                         for d in json.loads(u)["dishes"]]},
    )

    forecast = client.get("/v1/prepared-dishes/prep-forecast/").data["forecasts"][0]

    assert forecast["occurrence_dates"] == [(today - timedelta(weeks=k)).isoformat() for k in (1, 2, 3, 4)]
    assert forecast["occurrence_quantities"] == [2, 1, 8, 0]
