# Generated by Django 4.2.16 on 2026-09-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kdsdevice_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kdsdevice',
            options={'ordering': ['label', 'id']},
        ),
    ]
