# Generated by Django 4.2.16 on 2026-10-05 07:19

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_kdsdevice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kdsdevice',
            options={'ordering': [django.db.models.functions.text.Lower('label'), 'id']},
        ),
    ]
