# Generated by Django 4.2.16 on 2026-08-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('TENANT_CREATED', 'Tenant created'), ('TENANT_UPDATED', 'Tenant updated'), ('TEAM_MEMBER_ADDED', 'Team member added'), ('TEAM_MEMBER_DEACTIVATED', 'Team member deactivated')], max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='platform.platformadmin')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'platform_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
