# Generated by Django 4.2.16 on 2026-08-06 04:38

import apps.platform.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_org_identity_and_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platform', '0002_platformactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformadmin',
            name='access_level',
            field=models.CharField(choices=[('FULL_ADMIN', 'Full Admin'), ('SUPPORT_READONLY', 'Support (Read-only)')], default='FULL_ADMIN', max_length=20),
        ),
        migrations.AddField(
            model_name='platformadmin',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformactivitylog',
            name='action',
            field=models.CharField(choices=[('TENANT_CREATED', 'Tenant created'), ('TENANT_UPDATED', 'Tenant updated'), ('TEAM_MEMBER_ADDED', 'Team member added'), ('TEAM_MEMBER_DEACTIVATED', 'Team member deactivated'), ('TENANT_IMPERSONATED', 'Support access started'), ('IMPERSONATION_ENDED', 'Support access ended')], max_length=32),
        ),
        migrations.CreateModel(
            name='PlatformLoginCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.platform.models._generate_2fa_code, max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to='platform.platformadmin')),
            ],
            options={
                'db_table': 'platform_login_codes',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('platform_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions', to='platform.platformadmin')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions', to='restaurant.restaurant')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'impersonation_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
