# Generated by Django 4.2.16 on 2026-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_platformadmin_access_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdminBlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'platform_admin_blacklisted_tokens',
            },
        ),
        migrations.AlterField(
            model_name='platformactivitylog',
            name='action',
            field=models.CharField(choices=[('TENANT_CREATED', 'Org created'), ('TENANT_UPDATED', 'Tenant updated'), ('STATUS_CHANGED', 'Status changed'), ('FLAGS_CHANGED', 'Flags changed'), ('PLAN_CHANGED', 'Plan changed'), ('TEAM_MEMBER_ADDED', 'Team member added'), ('TEAM_MEMBER_DEACTIVATED', 'Team member deactivated'), ('TEAM_MEMBER_REMOVED', 'Team member removed'), ('TENANT_IMPERSONATED', 'Support access started'), ('IMPERSONATION_ENDED', 'Support access ended')], max_length=32),
        ),
    ]
