# Generated by Django 4.2.16 on 2026-08-06 13:31

import apps.platform.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0004_blacklisted_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.platform.models._generate_platform_refresh_token, max_length=80, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='platform.platformadmin')),
            ],
            options={
                'db_table': 'platform_refresh_tokens',
            },
        ),
    ]
