# Generated by Django 4.2.16 on 2026-09-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_refresh_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformactivitylog',
            name='action',
            field=models.CharField(choices=[('TENANT_CREATED', 'Org created'), ('TENANT_UPDATED', 'Tenant updated'), ('STATUS_CHANGED', 'Status changed'), ('FLAGS_CHANGED', 'Flags changed'), ('PLAN_CHANGED', 'Plan changed'), ('TEAM_MEMBER_ADDED', 'Team member added'), ('TEAM_MEMBER_DEACTIVATED', 'Team member deactivated'), ('TEAM_MEMBER_REMOVED', 'Team member removed'), ('TENANT_IMPERSONATED', 'Support access started'), ('IMPERSONATION_ENDED', 'Support access ended'), ('TENANT_DELETED', 'Organization permanently deleted')], max_length=32),
        ),
    ]
