# Generated by Django 4.2.16 on 2026-10-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_alter_platformactivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformactivitylog',
            name='action',
            field=models.CharField(choices=[('TENANT_CREATED', 'Org created'), ('TENANT_UPDATED', 'Tenant updated'), ('STATUS_CHANGED', 'Status changed'), ('FLAGS_CHANGED', 'Flags changed'), ('PLAN_CHANGED', 'Plan changed'), ('TEAM_MEMBER_ADDED', 'Team member added'), ('TEAM_MEMBER_DEACTIVATED', 'Team member deactivated'), ('TEAM_MEMBER_REMOVED', 'Team member removed'), ('TENANT_IMPERSONATED', 'Support access started'), ('IMPERSONATION_ENDED', 'Support access ended'), ('TENANT_DELETED', 'Organization permanently deleted'), ('SUBSCRIPTION_STARTED', 'Subscription started'), ('SUBSCRIPTION_PLAN_CHANGED', 'Subscription plan changed'), ('SUBSCRIPTION_PAYMENT_FAILED', 'Subscription payment failed'), ('SUBSCRIPTION_ENDED', 'Subscription ended')], max_length=32),
        ),
    ]
