# Generated by Django 4.2.16 on 2026-10-05 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0011_alter_restaurant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tier', models.CharField(max_length=16)),
                ('billing_cycle', models.CharField(default='MONTHLY', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_plan_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_key_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_razorpay_plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_tier', models.CharField(max_length=16)),
                ('billing_cycle', models.CharField(default='MONTHLY', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_plan_id', models.CharField(max_length=64)),
                ('razorpay_subscription_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Waiting for checkout'), ('AUTHENTICATED', 'Authorised, billing starts later'), ('ACTIVE', 'Active'), ('PENDING', 'Renewal failed, retrying'), ('HALTED', 'Renewals failed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CREATED', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('current_start', models.DateTimeField(blank=True, null=True)),
                ('current_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('plan_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='subscriptions.subscription')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_invoice_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('FAILED', 'Failed')], max_length=8)),
                ('method', models.CharField(blank=True, max_length=20)),
                ('plan_tier', models.CharField(max_length=16)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='restaurant.restaurant')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='razorpayplan',
            constraint=models.UniqueConstraint(fields=('plan_tier', 'billing_cycle', 'amount', 'razorpay_key_id'), name='one_razorpay_plan_per_price_and_key'),
        ),
    ]
