# Generated by Django 4.2.16 on 2026-09-09 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_parent_order'),
        ('tables', '0004_tablesession_bill_requested_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0005_restaurant_razorpay_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='CREATED', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='restaurant.restaurant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='tables.tablesession')),
            ],
            options={
                'db_table': 'payment_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order__isnull', True), ('session__isnull', False)), models.Q(('order__isnull', False), ('session__isnull', True)), _connector='OR'), name='payment_attempt_has_exactly_one_of_session_or_order'),
        ),
    ]
