# Generated by Django 4.2.16 on 2026-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='razorpay_qr_code_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('razorpay_order_id__isnull', False), ('razorpay_qr_code_id__isnull', True)), models.Q(('razorpay_order_id__isnull', True), ('razorpay_qr_code_id__isnull', False)), _connector='OR'), name='payment_attempt_has_exactly_one_of_order_or_qr_code'),
        ),
    ]
