# Generated by Django 4.2.16 on 2026-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentattempt_razorpay_qr_code_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('ONLINE', 'Online (method chosen in Checkout)'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=12),
        ),
    ]
