# Generated by Django 4.2.16 on 2026-07-22 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(max_length=32)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('NEEDS_CLEANING', 'Needs Cleaning')], default='AVAILABLE', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BILL_REQUESTED', 'Bill Requested'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('PAID', 'Paid'), ('MANAGER_OVERRIDE', 'Manager Override')], max_length=20)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table')),
            ],
            options={
                'db_table': 'table_sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'BILL_REQUESTED'])), fields=('table',), name='one_open_session_per_table'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_number'), name='one_table_number_per_restaurant'),
        ),
    ]
