# Generated by Django 4.2.16 on 2026-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_tablesession_assigned_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='bill_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
