# Generated by Django 4.2.16 on 2026-08-13 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_org_identity_and_plan'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('ALERT', 'Alert'), ('TIP', 'Tip')], max_length=8)),
                ('headline', models.CharField(max_length=255)),
                ('reason_breakdown', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=255)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to='restaurant.branch')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='inventory.ingredient')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-generated_at'],
            },
        ),
    ]
