# Generated by Django 4.2.16 on 2026-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_aiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
