# Generated by Django 4.2.16 on 2026-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reason',
            field=models.CharField(blank=True, choices=[('AI_ALERT', 'AI alert'), ('SUPPLIER_CALLED', 'Supplier called'), ('NOTICED', 'I noticed')], max_length=20),
        ),
    ]
