# Generated by Django 4.2.16 on 2026-09-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorder_is_emergency_purchaseorder_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'ordering': ['menu_item_id', 'id']},
        ),
    ]
