# Generated by Django 4.2.16 on 2026-09-21 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_alter_purchaseorderline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'goods_receipts',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('STOCK_COUNT_CORRECTION', 'Stock count correction'), ('WASTAGE', 'Wastage'), ('OPENING_STOCK', 'Opening stock'), ('GOODS_RECEIPT', 'Goods receipt')], max_length=32),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_RECEIVED', 'Partially received'), ('FULLY_RECEIVED', 'Fully received'), ('CLOSED', 'Closed')], default='PENDING_APPROVAL', max_length=32),
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsreceipt')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='inventory.purchaseorderline')),
            ],
            options={
                'db_table': 'goods_receipt_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
