# Generated by Django 4.2.16 on 2026-10-05 07:19

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_backfill_ai_insight_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': [django.db.models.functions.text.Lower('name'), 'id']},
        ),
    ]
