# Generated by Django 4.2.16 on 2026-08-06 06:11

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_address_must_change_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_index=True, default=apps.authentication.models._generate_reset_token, max_length=64),
        ),
    ]
