# Generated by Django 4.2.16 on 2026-08-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_org_identity_and_plan'),
        ('authentication', '0004_common_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurant.branch'),
        ),
    ]
