# Generated by Django 4.2.16 on 2026-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_READY', 'Order Ready'), ('BILL_REQUESTED', 'Bill Requested'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('LOW_STOCK', 'Low Stock'), ('STAFF_ADDED', 'Staff Added'), ('PREP_LOGGED', 'Prep Logged')], max_length=32),
        ),
    ]
