# Generated by Django 4.2.16 on 2026-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_READY', 'Order Ready'), ('BILL_REQUESTED', 'Bill Requested'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('LOW_STOCK', 'Low Stock'), ('STAFF_ADDED', 'Staff Added'), ('PREP_LOGGED', 'Prep Logged'), ('PURCHASE_ORDER_RAISED', 'Purchase Order Raised'), ('PURCHASE_ORDER_APPROVED', 'Purchase Order Approved'), ('PURCHASE_ORDER_REJECTED', 'Purchase Order Rejected'), ('PURCHASE_ORDER_ORDERED', 'Purchase Order Ordered')], max_length=32),
        ),
    ]
